add login
Aung-Phone-Naing/Attendance_Tracking pull request #1
Opened 2024-10-07 10:12 UTC by Whysochong

2024-10-07 19:44 UTC, Aung-Phone-Naing requested changes
I think generally all goods, just remove the .env and answer the comment for the declaration. Perhaps you can take a look at the structure for the schema branch, I have firmed up the routes, handlers and query functions for a cleaner approach.

2024-10-07 19:44 UTC, Aung-Phone-Naing commented on .env
Remove this file.

2024-10-07 19:44 UTC, Aung-Phone-Naing commented on backend/src/types/express/index.d.ts
Whats this declaration for?

2024-10-12 13:13 UTC, Whysochong commented on backend/src/types/express/index.d.ts
It helps with TypeScript typing so that `req.user` is a valid property, and it can provide type checking.

2024-10-12 13:22 UTC, merged